- book/0 - Introduction/2 - What is MCServer.html
> Fixed Gratipay link

- book/1 - Installing/2 - Compiling Cuberite Yourself.html
- book/1 - Installing/3 - Running Cuberite.html
Changed the command to run the server, and the folder it compiles into. (I couldn't find the server when I was looking for `MCServer`)
> Fixed compile/run command

- book/1 - Installing/2 - Compiling Cuberite Yourself.html
> Fixed capitalization

- book/0 - Introduction/1 - Introduction.html
- book/0 - Introduction/2 - What is Cuberite.html
- book/1 - Installing/1 - Pre-Compiled Builds.html
- book/1 - Installing/2 - Compiling Cuberite Yourself.html
- book/2 - Configuration Basics/1 - Configuration overview.html
- book/2 - Configuration Basics/3 - Worlds.html
- book/3 - Configuring world.ini/1 - What is world.ini.html
Reverts cuberite/users-manual#35
> Revert "Print-friendly book"

- book/0 - Introduction/1 - Introduction.html
- book/2 - Configuration Basics/3 - Worlds.html
How stable are multiworlds? Should I add a stability warning in `Multiple Worlds`?
> Added a resources paragraph, minor Worlds changes

- book/3 - Configuring world.ini/4 - Storage.html
> Clean non ascii chars

- book/0 - Introduction/1 - Introduction.html
- book/0 - Introduction/3 - History.html
- book/1 - Installing/1 - Pre-Compiled Builds.html
- book/2 - Configuration Basics/1 - Configuration overview.html
- book/3 - Configuring world.ini/1 - What is world.ini.html
- book/3 - Configuring world.ini/4 - Storage.html
A few word fixes, after reading trough it :)
> Fixed words and renamed Github to GitHub

- book/1 - Installing/2 - Compiling Cuberite Yourself.html
> Consistency with compiling.md

- book/0 - Introduction/3 - History.html
Preparing this in advance. Do not merge until > 1000
> 1000 stars

- book/2 - Configuration Basics/1 - Configuration Overview.html
- book/2 - Configuration Basics/3 - Worlds.html
- book/2 - Configuration Basics/4 - Plugins.html
- book/4 - MultiWorlds/1 - Multiworlds Overview.html
- book/4 - MultiWorlds/2 - Traveling by Command.html
- book/4 - MultiWorlds/3 - Linking Worlds with a Plugin.html
- book/4 - MultiWorlds/4 - Linking Worlds Without Plugins.html
> Multiworlds

- book/2 - Configuration Basics/1 - Configuration Overview.html
- book/2 - Configuration Basics/3 - Worlds.html
- book/4 - MultiWorlds/1 - Multiworlds Overview.html
To be merged once https://github.com/cuberite/cuberite/pull/2815 is merged.
> 3 Worlds by default

- book/4 - MultiWorlds/1 - Multiworlds Overview.html
Merge if https://github.com/cuberite/cuberite/pull/2953 is merged.
> Advise on appending _end / _nether to world names

- book/4 - MultiWorlds/1 - Multiworlds Overview.html
Reverts cuberite/users-manual#61
> Revert "Advise on appending _end / _nether to world names"

- book/4 - MultiWorlds/1 - Multiworlds Overview.html
Identical to #61.
Do NOT merge before https://github.com/cuberite/cuberite/pull/2953 is merged :P
> Explained how to use suffixes to create nether or end type worlds

- book/2 - Configuration Basics/1 - Configuration Overview.html
> favicon instructions

- book/3 - Configuring world.ini/3 - GameMode.html
- book/3 - Configuring world.ini/4 - Storage.html
- Added adventure and spectator mode to gamemode section
- Removed "Compact" schema, since it doesn't exist anymore
> Corrections

- book/1 - Installing/2 - Compiling Cuberite Yourself.html
This follows cuberite/cuberite#3279
> Changed CROSSCOMPILE to NO_NATIVE_OPTIMIZATION.

- book/2 - Configuration Basics/1 - Configuration Overview.html
- book/2 - Configuration Basics/4 - Worlds.html
- book/4 - MultiWorlds/1 - Multiworlds Overview.html
> Changed world_end to world_the_end

- .travis.yml
- generate.py
- template.html
> Link to latest commit and proper update date

- .travis.yml
> Fix Java installation on Travis CI

- template.html
As discussed in https://github.com/cuberite/cuberite.github.io/issues/91
> Remove analytics code

- book/2 - Configuration Basics/3 - WebAdmin.html
I try to make it clear that you need to enable the web admin in the first place. 
In my opinion this isn't made clear
> Added line about enabling the webadmin

- book/3 - Configuring world.ini/11 - Generator.html
New values for cuberite/cuberite#5552
> Updated EndGen documentation
